basePath: /
info:
  contact: {}
  title: User API documentation
paths:
  /api/v1/films:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: ListAllFilms
      tags:
      - Film service
swagger: "2.0"
