basePath: /
definitions:
  auth.CheckOTPRequest:
    properties:
      otp:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
  title: User API documentation
paths:
  /api/v1/auth/check_otp:
    post:
      consumes:
      - application/json
      parameters:
      - description: CheckOTP
        in: body
        name: checkOTPRequest
        required: true
        schema:
          $ref: '#/definitions/auth.CheckOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Check otp with phone number, return jwt token
      tags:
      - Auth service
  /api/v1/cinema/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: cinema id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: GetCinemaById
      tags:
      - Cinema service
  /api/v1/cinemas:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: ListAllCinemas
      tags:
      - Cinema service
  /api/v1/film/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: GetFilmById
      tags:
      - Film service
  /api/v1/films:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: ListAllFilms
      tags:
      - Film service
  /api/v1/films/{category}:
    get:
      consumes:
      - application/json
      parameters:
      - description: action
        in: path
        name: category
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: ListFilmsByCategory
      tags:
      - Film service
  /api/v1/schedules:
    get:
      consumes:
      - application/json
      parameters:
      - description: cinemaId
        in: query
        name: cinemaId
        type: integer
      - description: filmId
        in: query
        name: filmId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: ListSchedules
      tags:
      - Schedule service
swagger: "2.0"
